Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 2048
      Handler: co.epam.Handler
      CodeUri: /home/jojaynu/Documents/Projects/Java/learning-java/java-advanced/java-with-dynamo-db
      Runtime: java11
      Architectures:
        - x86_64